/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.controltec;

import com.github.britooo.looca.api.core.Looca;
import com.mycompany.controltec.entidades.Componentes;
import com.mycompany.controltec.entidades.Maquina;
import com.mycompany.controltec.entidades.UsoDeMaquina;
import com.mycompany.controltec.entidades.Usuario;
import com.mycompany.controltec.jdbc.Conexao;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 *
 * @author Lenovo
 */
public class TelaDeLogin extends javax.swing.JFrame {

    Conexao conexao = new Conexao();
    JdbcTemplate con = new JdbcTemplate(conexao.getDataSource());
    Looca looca = new Looca();

    /**
     * Creates new form TelaDeLogin
     */
    public TelaDeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagensFundo = new javax.swing.JLabel();
        lblRA = new javax.swing.JFormattedTextField();
        btnEntrar = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        nameRA = new javax.swing.JLabel();
        nameSENHA = new javax.swing.JLabel();
        labelEmpresa = new javax.swing.JLabel();
        lblSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela De Login");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        lblRA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRAActionPerformed(evt);
            }
        });
        getContentPane().add(lblRA);
        lblRA.setBounds(200, 90, 120, 20);

        btnEntrar.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(190, 200, 70, 21);

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("Exit");
        btnExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(270, 200, 70, 21);

        nameRA.setBackground(new java.awt.Color(255, 255, 255));
        nameRA.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nameRA.setForeground(new java.awt.Color(255, 255, 255));
        nameRA.setText("LOGIN:");
        getContentPane().add(nameRA);
        nameRA.setBounds(200, 70, 60, 16);

        nameSENHA.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nameSENHA.setForeground(new java.awt.Color(255, 255, 255));
        nameSENHA.setText("SENHA:");
        getContentPane().add(nameSENHA);
        nameSENHA.setBounds(200, 120, 60, 16);

        labelEmpresa.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        labelEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        labelEmpresa.setText("Control Tec - Faça seu Login");
        getContentPane().add(labelEmpresa);
        labelEmpresa.setBounds(100, 10, 300, 50);

        lblSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(lblSenha);
        lblSenha.setBounds(200, 140, 120, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tecnologia2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 270);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tecnologia2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, -10, 664, 417);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:

        String ra = lblRA.getText();
        String senha = lblSenha.getText();
        Long idMaquina = 0L;
        String identificador = looca.getProcessador().getId();
        UsoDeMaquina udm = new UsoDeMaquina();
        Integer contador = 0;


        List<Usuario> listaDeUsuarios = con.query("select * from dbo.Usuario where email = '" + ra + "' "
                + "AND senha = '" + senha + "';",
                new BeanPropertyRowMapper(Usuario.class));

        List<Maquina> listaDeMaquinas = con.query("select * from dbo.Maquina ",
                new BeanPropertyRowMapper(Maquina.class));

        for (Maquina maquinas : listaDeMaquinas) {
            if (maquinas.getIdentificador().equals(identificador)) {
                idMaquina = maquinas.getIdMaquina();
            }          
        }
        if(idMaquina <= 0){
           JOptionPane.showMessageDialog(null, "Máquina não encontrada,"
                   + "Entre em contato com a sua instituição"); 
        }
        
        List<Componentes> listaDeComponentes = con.query("select * from dbo.Componentes where fkMaquina = '" + idMaquina + "'; ",
                new BeanPropertyRowMapper(Componentes.class));

        
        if (listaDeUsuarios.isEmpty()) {
            System.out.println("Erro");
            JOptionPane.showMessageDialog(null, "Login e/ou senha inválidos");
        } else {
            System.out.println("Logado com sucesso");
            JOptionPane.showMessageDialog(null, String.format("Seja bem vindo %s \n"
                    + "A captura de dados irá começar assim que o botão 'OK' for clicado"
                    , listaDeUsuarios.get(0).getNome()));

            try {
                while (true) {
                    contador ++;
                    System.out.println(String.format("Captura de Dados N°%d", contador));
                    for (Componentes componente : listaDeComponentes) {
                        udm.capturarDados(listaDeUsuarios.get(0), componente);
                    }
                    Thread.sleep(200L);
                }
            } catch (Exception ex) {
                Logger.getLogger(TelaDeLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void lblRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRAActionPerformed

    private void lblSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel imagensFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelEmpresa;
    private javax.swing.JFormattedTextField lblRA;
    private javax.swing.JPasswordField lblSenha;
    private javax.swing.JLabel nameRA;
    private javax.swing.JLabel nameSENHA;
    // End of variables declaration//GEN-END:variables
}
